apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookkeeping-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bookkeeping

  source:
    repoURL: https://github.com/Tesseract-Nexus/bookkeeping-app.git
    targetRevision: main
    path: argocd/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
