apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookkeeping-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: bookkeeping
    app.kubernetes.io/instance: dev
    app.kubernetes.io/component: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bookkeeping

  source:
    repoURL: https://github.com/Tesseract-Nexus/bookkeeping-app.git
    targetRevision: main
    path: charts/bookkeeping-app
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
      parameters:
        - name: global.env
          value: dev
        - name: global.image.tag
          value: main

  destination:
    server: https://kubernetes.default.svc
    namespace: bookkeeping-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health checks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
